/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Admin.QuanLyTrongTai;
import Controller.trongtaicontroller.TrongTaiController;
import Model.TrongTai;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.*;
import java.util.List;
/**
 *
 * @author ntnfa
 */
public class TrongTaiPanel extends javax.swing.JPanel {
    private TrongTaiController controller;

    private JTextField txtTimKiem;
    private JButton btnTimKiem, btnThem, btnSua, btnXoa;
    private JTable tblTrongTai;
    private DefaultTableModel model;
    /**
     * Creates new form TrongTaiPanel
     */
    
    public TrongTaiPanel() {
        setLayout(new BorderLayout());

        JPanel panelTop = new JPanel();
        panelTop.add(new JLabel("Tìm kiếm theo tên:"));
        txtTimKiem = new JTextField(20);
        btnTimKiem = new JButton("Tìm kiếm");
        panelTop.add(txtTimKiem);
        panelTop.add(btnTimKiem);

        model = new DefaultTableModel(new Object[]{"Mã", "Tên trọng tài", "Ngày sinh", "Quốc gia"}, 0);
        tblTrongTai = new JTable(model);
        JScrollPane scrollPane = new JScrollPane(tblTrongTai);

        JPanel panelBottom = new JPanel();
        btnThem = new JButton("Thêm");
        btnSua = new JButton("Sửa");
        btnXoa = new JButton("Xóa");
        panelBottom.add(btnThem);
        panelBottom.add(btnSua);
        panelBottom.add(btnXoa);

        add(panelTop, BorderLayout.NORTH);
        add(scrollPane, BorderLayout.CENTER);
        add(panelBottom, BorderLayout.SOUTH);

        controller = new TrongTaiController(this);

        btnTimKiem.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                controller.timKiemTrongTai();
            }
        });
        btnThem.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                controller.moFormThemTrongTai();
            }
        });
        btnSua.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                controller.moFormSuaTrongTai();
            }
        });
        btnXoa.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                controller.xoaTrongTai();
            }
        });

        controller.loadTatCaTrongTai();
    }

    public String getTuKhoaTimKiem() {
        return txtTimKiem.getText().trim();
    }

    public void hienThiDanhSachTrongTai(List<TrongTai> list) {
        model.setRowCount(0);
        for (TrongTai tt : list) {
            model.addRow(new Object[]{
                tt.getMaTrongTai(),
                tt.getTenTrongTai(),
                tt.getNgaySinh(),
                tt.getQuocGia().getTenQuocGia()
            });
        }
    }

    public int getMaTrongTaiDangChon() {
        int row = tblTrongTai.getSelectedRow();
        if (row == -1) {
            return -1;
        }
        return (int) model.getValueAt(row, 0);
    }

    public void hienThongBao(String message) {
        JOptionPane.showMessageDialog(this, message);
    }

    public boolean hoiXacNhan(String message) {
        int result = JOptionPane.showConfirmDialog(this, message, "Xác nhận", JOptionPane.YES_NO_OPTION);
        return result == JOptionPane.YES_OPTION;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
